### ISSUE TITLE
Good Library

### ISSUE THREAD

**Issue by schuppeste** [fricklr/TeeOnArdu#6]
Hi, i have a custom Board and i need alls IOs.

Whyever PD5 is LOW on boot, Pullup and input not Work.

on other side Pin PE6 is doublette as Pin7 and Pin 24, so i have changed Pin24 to PD5.

**Comment by schuppeste** [comment]
i have found it..
D7 And D12 defines same BIT on PORTD.

**Comment by fricklr** [comment]
Hi,
please note that this code is no longer maintained. It has been very useful 5 years ago. Please use https://github.com/arduino-libraries/MIDIUSB now.
Cheers
